services:
  postgres:
    container_name: pp-postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: passedpawn
    networks:
      - api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d passedpawn"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s


  pgadmin:
    container_name: pp-pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - api-network

  api:
    container_name: pp-api
    build:
      context: .
      dockerfile: Dockerfile
    image: pp-api
    ports: 
      - 8080:8080
    networks:
      - api-network
    volumes:
      - ./PassedPawn.API/appsettings.Development.json:/app/config/appsettings.json
    depends_on: 
      postgres:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'if echo -n > /dev/tcp/localhost/8080; then exit 0; else exit 1; fi'"]
      interval: 10s
      retries: 3
      start_period: 15s
      timeout: 10s

  keycloak:
    container_name: pp-keycloak
    image: quay.io/keycloak/keycloak:26.0.5
    ports:
      - 8081:8080
    command: -v start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: keycloak-postgres
      DB_PORT: ${KEYCLOAK_POSTGRES_DB_PORT}
      DB_DATABASE: ${KEYCLOAK_POSTGRES_DB}
      DB_USER: ${KEYCLOAK_POSTGRES_USER}
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - keycloak-network
      - api-network

  keycloak-postgres:
    container_name: pp-keycloak-postgres
    image: postgres
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    networks:
      - keycloak-network
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

networks:
  keycloak-network:
  api-network:

volumes:
  keycloak-db-data: