// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PassedPawn.DataAccess;

#nullable disable

namespace PassedPawn.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250510072517_MadePositionNumericalInArrowsAndHighlights")]
    partial class MadePositionNumericalInArrowsAndHighlights
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoursePuzzleStudent", b =>
                {
                    b.Property<int>("PuzzlesId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsId")
                        .HasColumnType("integer");

                    b.HasKey("PuzzlesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CoursePuzzleStudent");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsId")
                        .HasColumnType("integer");

                    b.HasKey("CoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChessTitle")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DetailedDescription")
                        .HasColumnType("text");

                    b.Property<int>("Elo")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NationalityId");

                    b.HasIndex("PhotoId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.CourseReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseReviews");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EloRangeEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("EloRangeStart")
                        .HasColumnType("integer");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("ReleaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ThumbnailId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("ThumbnailId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("InitialDescription")
                        .HasColumnType("text");

                    b.Property<string>("InitialFen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("LessonId");

                    b.ToTable("CourseExamples");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExampleMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgebraicNotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ExampleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExampleId");

                    b.ToTable("CourseExampleMove");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExampleMoveArrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Destination")
                        .HasColumnType("integer");

                    b.Property<int>("ExampleMoveId")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExampleMoveId");

                    b.ToTable("CourseExampleMoveArrow");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExampleMoveHighlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExampleMoveId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExampleMoveId");

                    b.ToTable("CourseExampleMoveHighlight");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CoursePuzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("CoursePuzzles");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("Fen")
                        .HasColumnType("text");

                    b.Property<string>("Hint")
                        .HasColumnType("text");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("CourseQuizes");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("CourseVideos");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.QuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastMove")
                        .HasColumnType("text");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizAnswer");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Preview")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FlagId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("FlagId");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "United States",
                            ShortName = "USA"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Canada",
                            ShortName = "CAN"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "United Kingdom",
                            ShortName = "UK"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Australia",
                            ShortName = "AUS"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Germany",
                            ShortName = "GER"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "France",
                            ShortName = "FRA"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Italy",
                            ShortName = "ITA"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Spain",
                            ShortName = "ESP"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Japan",
                            ShortName = "JPN"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "China",
                            ShortName = "CHN"
                        },
                        new
                        {
                            Id = 11,
                            FullName = "India",
                            ShortName = "IND"
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Brazil",
                            ShortName = "BRA"
                        },
                        new
                        {
                            Id = 13,
                            FullName = "Mexico",
                            ShortName = "MEX"
                        },
                        new
                        {
                            Id = 14,
                            FullName = "Russia",
                            ShortName = "RUS"
                        },
                        new
                        {
                            Id = 15,
                            FullName = "South Africa",
                            ShortName = "RSA"
                        },
                        new
                        {
                            Id = 16,
                            FullName = "South Korea",
                            ShortName = "KOR"
                        },
                        new
                        {
                            Id = 17,
                            FullName = "Argentina",
                            ShortName = "ARG"
                        },
                        new
                        {
                            Id = 18,
                            FullName = "Saudi Arabia",
                            ShortName = "KSA"
                        },
                        new
                        {
                            Id = 19,
                            FullName = "Turkey",
                            ShortName = "TUR"
                        },
                        new
                        {
                            Id = 20,
                            FullName = "Netherlands",
                            ShortName = "NED"
                        },
                        new
                        {
                            Id = 21,
                            FullName = "Sweden",
                            ShortName = "SWE"
                        },
                        new
                        {
                            Id = 22,
                            FullName = "Switzerland",
                            ShortName = "CHE"
                        },
                        new
                        {
                            Id = 23,
                            FullName = "Poland",
                            ShortName = "POL"
                        },
                        new
                        {
                            Id = 24,
                            FullName = "Egypt",
                            ShortName = "EGY"
                        },
                        new
                        {
                            Id = 25,
                            FullName = "Nigeria",
                            ShortName = "NGA"
                        });
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChessTitle")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Elo")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NationalityId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoursePuzzleStudent", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Elements.CoursePuzzle", null)
                        .WithMany()
                        .HasForeignKey("PuzzlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PassedPawn.DataAccess.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PassedPawn.DataAccess.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Coach", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("PassedPawn.DataAccess.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.Navigation("Nationality");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.CourseReview", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PassedPawn.DataAccess.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Course", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Coach", "Coach")
                        .WithMany("Courses")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PassedPawn.DataAccess.Entities.Photo", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId");

                    b.Navigation("Coach");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExample", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Course", null)
                        .WithMany("Examples")
                        .HasForeignKey("CourseId");

                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Lesson", "Lesson")
                        .WithMany("Examples")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExampleMove", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExample", "Example")
                        .WithMany("Moves")
                        .HasForeignKey("ExampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Example");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExampleMoveArrow", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExampleMove", "ExampleMove")
                        .WithMany("Arrows")
                        .HasForeignKey("ExampleMoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExampleMove");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExampleMoveHighlight", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExampleMove", "ExampleMove")
                        .WithMany("Highlights")
                        .HasForeignKey("ExampleMoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExampleMove");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CoursePuzzle", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Lesson", "Lesson")
                        .WithMany("Puzzles")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseQuiz", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Lesson", "Lesson")
                        .WithMany("Quizzes")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseVideo", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Lesson", "Lesson")
                        .WithMany("Videos")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.QuizAnswer", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Elements.CourseQuiz", "Quiz")
                        .WithMany("Answers")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Lesson", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Courses.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Nationality", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Photo", "Flag")
                        .WithMany()
                        .HasForeignKey("FlagId");

                    b.Navigation("Flag");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Student", b =>
                {
                    b.HasOne("PassedPawn.DataAccess.Entities.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Coach", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Course", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Lessons");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExample", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseExampleMove", b =>
                {
                    b.Navigation("Arrows");

                    b.Navigation("Highlights");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Elements.CourseQuiz", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("PassedPawn.DataAccess.Entities.Courses.Lesson", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Puzzles");

                    b.Navigation("Quizzes");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
